[settings]
welcome_text = "Sup yo? Enjoy"
orientation = 180
notification_path = "../notification"
sleep_timeout = 240                   # -- 240 seems to be the maximum
wheel_step = 3

# --| Button 0 -------------------
[buttons.0]
text = "PC +2%"
command = "result=$(/mnt/x/GitHub/instance-id/typescript/quick-keys-app/scripts/vol_up.ps1); echo $result"

[buttons.0.press_overlay]
duration = 1
text = "Volume Up: %output%"

# --| Button 1 -------------------
[buttons.1]
text = "_____"
command = "echo 'Button 1 pressed'"

[buttons.1.press_overlay]
duration = 1
text = "Command issued"

# --| Button 2 -------------------
[buttons.2]
text = "Script"
command = "/home/mosthated/_dev/languages/pwsh/random/ps_test_1.ps1"

[buttons.2.press_overlay]
duration = 1
text = "Command issued"

# --| Button 3 -------------------
[buttons.3]
text = "Password"
command = "rofi-rbw -a copy"

[buttons.3.press_overlay]
duration = 1
text = "Command issued"

# --| Button 4 -------------------
[buttons.4]
text = "PC -2%"
command = "result=$(/mnt/x/GitHub/instance-id/typescript/quick-keys-app/scripts/vol_down.ps1); echo $result"

[buttons.4.press_overlay]
duration = 1
text = "Volume Down: %output%"

# --| Button 5 -------------------
[buttons.5]
text = "_____"
command = "echo 'Button 5 pressed'"

[buttons.5.press_overlay]
duration = 1
text = "Command issued"

# --| Button 6 -------------------
[buttons.6]
text = "_____"
command = "echo 'Button 6 pressed'"

[buttons.6.press_overlay]
duration = 1
text = "Command issued"

# --| Button 7 -------------------
[buttons.7]
text = "Source"
command = "current_output=$(/mnt/x/GitHub/instance-id/typescript/quick-keys-app/scripts/change_output.ps1); echo $current_output"

[buttons.7.press_overlay]
duration = 2
# -- Response with %% has the symbols replaced with the output of the command ran
# -- If response is too long, it will be truncated
text = "Source Selected: %output%.%"

# --| Button 8 -------------------
[buttons.8]
text = ""
command = "reload_config"

[buttons.8.press_overlay]
duration = 1
text = "Config Reloaded"

# --| Button 9 -------------------
[buttons.9]
text = ""
command = "echo 'Button 9 pressed'"

[buttons.9.press_overlay]
duration = 1
text = "Wheel Button"

# --| Wheel ----------------------
[wheel]
color = [255, 0, 180]

[wheel.left]
command = "amixer set Master 2%- > /dev/null 2>&1 && results=$(amixer sget Master | awk -F\"[][]\" '/Left:/ { print $2 }'); echo $results"

[wheel.left.press_overlay]
duration = 1
text = "Volume Down"

[wheel.right]
command = "amixer set Master 2%+ > /dev/null 2>&1 && results=$(amixer sget Master | awk -F\"[][]\" '/Left:/ { print $2 }'); echo $results"


[wheel.right.press_overlay]
duration = 1
text = "Volume Up"
